# Generated by Django 4.2.4 on 2023-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_bouquetcomponent_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Заказ оплачен?'),
        ),
    ]
